### ISSUE TITLE
https://bootstrap.pypa.io/get-pip.py doesn't work with Python 2.7.6 or earlier 2.7s

### ISSUE THREAD

**Issue by csm10495** [pypa/get-pip#26]
Trying to get-pip doesn't work anymore on older 2.7s. I think it has to do with tls1.2 being required and probably not supported in older Python 2.7s. How can I install and use pip on Python 2.7.6 and earlier 2.7s?

Log from Python 2.7.6 get-pip:
```
c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\_vendor\urllib3\util\ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),)': /packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl
c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),)': /packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl
c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),)': /packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl
c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),)': /packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl
c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),)': /packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl
c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Exception:
Traceback (most recent call last):
  File "c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\download.py", line 659, in unpack_http_url
    hashes)
  File "c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\download.py", line 853, in _download_http_url
    stream=True,
  File "c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\_vendor\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\_vendor\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\_vendor\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\_vendor\cachecontrol\adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\csm10495\appdata\local\temp\tmp2cs1sz\pip.zip\pip\_vendor\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl (Caused by SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),))
```

**Comment by hugovk** [comment]
Not sure what the difference is, but looks like get-pip.py works on Python 2.7.6 on Travis CI:

```console
$ .travis/helpers.sh "$TRAVIS_PYTHON_VERSION" "$SCRIPT_SRC"
Downloading bootstrap script from remote...
Version 2.7.6 requires following script: https://bootstrap.pypa.io/get-pip.py
--2018-04-18 20:22:47--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.200.175, 2a04:4e42:8::175
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.200.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1641282 (1.6M) [text/x-python]
Saving to: ‘STDOUT’
100%[======================================>] 1,641,282   --.-K/s   in 0.03s   
2018-04-18 20:22:47 (45.6 MB/s) - written to stdout [1641282/1641282]
Collecting pip
/tmp/tmpqQ9Zom/pip.zip/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
/tmp/tmpqQ9Zom/pip.zip/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
/tmp/tmpqQ9Zom/pip.zip/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
/tmp/tmpqQ9Zom/pip.zip/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Downloading https://files.pythonhosted.org/packages/62/a1/0d452b6901b0157a0134fd27ba89bf95a857fbda64ba52e1ca2cf61d8412/pip-10.0.0-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 17.5MB/s 
Collecting setuptools
/tmp/tmpqQ9Zom/pip.zip/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Downloading https://files.pythonhosted.org/packages/20/d7/04a0b689d3035143e2ff288f4b9ee4bf6ed80585cc121c90bfd85a1a8c2e/setuptools-39.0.1-py2.py3-none-any.whl (569kB)
    100% |████████████████████████████████| 573kB 27.9MB/s 
Installing collected packages: pip, setuptools
Successfully installed pip-10.0.0 setuptools-39.0.1
The command ".travis/helpers.sh "$TRAVIS_PYTHON_VERSION" "$SCRIPT_SRC"" exited with 0.
$ pip -V
pip 10.0.0 from /home/travis/virtualenv/python2.7.6/lib/python2.7/site-packages/pip (python 2.7)
```

https://travis-ci.org/hugovk/get-pip/jobs/368333788

https://travis-ci.org/hugovk/get-pip/builds/368333772

**Comment by webknjaz** [comment]
Probably Windows version is shipped with an outdated TLS support

**Comment by webknjaz** [comment]
yes, this is my best guess.

**Comment by csm10495** [comment]
@pradyunsg, sure... Seems about the same with the latest:
```
c:\users\csm10495\appdata\local\temp\tmpix4elz\pip.zip\pip\_vendor\urllib3\util\ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
c:\users\csm10495\appdata\local\temp\tmpix4elz\pip.zip\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),)': /simple/pip/
c:\users\csm10495\appdata\local\temp\tmpix4elz\pip.zip\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),)': /simple/pip/
c:\users\csm10495\appdata\local\temp\tmpix4elz\pip.zip\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),)': /simple/pip/
c:\users\csm10495\appdata\local\temp\tmpix4elz\pip.zip\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),)': /simple/pip/
c:\users\csm10495\appdata\local\temp\tmpix4elz\pip.zip\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),)': /simple/pip/
c:\users\csm10495\appdata\local\temp\tmpix4elz\pip.zip\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),)) - skipping
  Could not find a version that satisfies the requirement pip (from versions: )
No matching distribution found for pip
```

**Comment by pradyunsg** [comment]
AFAICT you'd need to install urllib3's `secure` extra but I'm not sure how you can do that without a working pip. None the less, the relevant resource: https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2 -- pip would be able to use these to establish a secure communication channel.

**Comment by csm10495** [comment]
@pradyunsg, I went through a round-about way to get pip, and urllib3[secure] (using manually downloaded wheels and --no-index) though even then I still can't pip install a module from pypi:

```
PS C:\Users\csm10495\Desktop\PyNPipInst\PyNPipInst> python2 -m pip install urllib3[secure]
Requirement already satisfied: urllib3[secure] in c:\python27\lib\site-packages (1.22)
Requirement already satisfied: idna>=2.0.0; python_version <= "2.7" and extra == "secure" in c:\python27\lib\site-packages (from urllib3[secure]) (2.6)
Requirement already satisfied: pyOpenSSL>=0.14; python_version <= "2.7" and extra == "secure" in c:\python27\lib\site-packages (from urllib3[secure]) (17.5.0)
Requirement already satisfied: cryptography>=1.3.4; python_version <= "2.7" and extra == "secure" in c:\python27\lib\site-packages (from urllib3[secure]) (2.2.2)
Requirement already satisfied: certifi; extra == "secure" in c:\python27\lib\site-packages (from urllib3[secure]) (2018.4.16)
Requirement already satisfied: ipaddress; python_version <= "2.7" and extra == "secure" in c:\python27\lib\site-packages (from urllib3[secure]) (1.0.22)
Requirement already satisfied: six>=1.5.2 in c:\python27\lib\site-packages (from pyOpenSSL>=0.14; python_version <= "2.7" and extra == "secure"->urllib3[secure]) (1.11.0)
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in c:\python27\lib\site-packages (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure]) (1.11.5)
Requirement already satisfied: enum34; python_version < "3" in c:\python27\lib\site-packages (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure]) (1.1.6)
Requirement already satisfied: asn1crypto>=0.21.0 in c:\python27\lib\site-packages (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure]) (0.24.0)
Requirement already satisfied: pycparser in c:\python27\lib\site-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure]) (2.18)
PS C:\Users\csm10495\Desktop\PyNPipInst\PyNPipInst> python2 -m pip install serial
Collecting serial
C:\Python27\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
C:\Python27\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),)': /simple/serial/
C:\Python27\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),)': /simple/serial/
C:\Python27\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),)': /simple/serial/
C:\Python27\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),)': /simple/serial/
C:\Python27\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),)': /simple/serial/
C:\Python27\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
  Could not fetch URL https://pypi.org/simple/serial/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/serial/ (Caused by SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),)) - skipping
  Could not find a version that satisfies the requirement serial (from versions: )
No matching distribution found for serial
PS C:\Users\csm10495\Desktop\PyNPipInst\PyNPipInst> python2 -m pip --version
pip 10.0.1 from C:\Python27\lib\site-packages\pip (python 2.7)
PS C:\Users\csm10495\Desktop\PyNPipInst\PyNPipInst> python2 --version
Python 2.7.6
```

**Comment by sfGLC** [comment]
After I updated the get-pip.py on Windows 7, the error messages are identical to the Windows Server 2012.

**Comment by razzor12** [comment]
I'm having the same problem, and I'm looking for any novelty solution I come back here to show.

**Comment by 3dprogramin** [comment]
Having the same issue on Windows Server 2012 R2 Datacenter

**Comment by 3dprogramin** [comment]
Solved it by installing the latest version of python2 (2.7.15 currently) from here: https://www.python.org/downloads/ 
Comes with pip included.

**Comment by pradyunsg** [comment]
It might just be that pip on the older Python versions is no longer capable of communicating to PyPI. :/

I'm out of my depth here. @ewdurbin or @dstufft would likely know more than me.

**Comment by ewdurbin** [comment]
It’s likely whatever SSL is available in the older 2.7 builds for Windows not supporting TLSv1.2

I’m not familiar with the Windows builds, but if we know what versions of OpenSSL they’re built against, that’d probably make things clear. @zooba... maybe you have info.

I’ll take a closer look next week, but an old Python built with an old OpenSSL (version < 1.0.1) seems like the most likely issue here.

**Comment by zooba** [comment]
I don't recall what version shipped in 2.7.6 (before my time), but in 2.7.15 we should be on 1.0.1.

**Comment by megamos** [comment]
Could not use command to download and run get-pip.py, but found command that worked for me on stackoverflow:
``
$ wget https://bootstrap.pypa.io/get-pip.py
$ sudo python2.7 get-pip.py
``

**Comment by ricardolopes86** [comment]
Hey Folks,

did anyone get a solution for this? 

I don't have access to root or sudo isn't an option. I tried to install urllib3[secure], but it didn't work for me: No module named pip

My python version is 2.7.2.

Any ideas on how to get it working?

**Comment by webknjaz** [comment]
@ricardolopes86 download https://bootstrap.pypa.io/get-pip.py manually and copy it to your target system. then, run it with whatever python you need.

**Comment by pradyunsg** [comment]
This is expected, pip only supports the latest patch version of any Python X.Y. If anyone is still hitting this in 2021, they should really be migrating to Python 3. :)
